### ISSUE TITLE
Invert Y-Axis

### ISSUE THREAD

**Issue by andrewcameronsims** [JoshTeperman/Termino-visual#10]
# Invert the Y-Axis!
At present, we are drawing the Y-axis upside down. This is a product of the fact that curses starts counting lines from the top of the screen, rather than from the bottom. This should be easily fixed.

**Comment by JoshTeperman** [comment]
Solved - Subtract y-coordinate for each observation from screen height, and x-coordinate from screen width when specifying Curses.setpos() to invert
