### ISSUE TITLE
Data overlapping with y-Axis

### ISSUE THREAD

**Issue by JoshTeperman** [JoshTeperman/Termino-visual#14]
screen width / height are being directly calculated by the max/min values of the data set we are using, resulting in several issues with visualisation: 

- January data starts at line 1, which overlaps with y-axis line
- Similarly, max temperatures are used to set the coordinates on y axis meaning the data is pushed to the top of the screen.

**Comment by andrewcameronsims** [comment]
This is fixed, axes and numbers render properly.
